name       : mate-session-manager
version    : 1.20.0
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-session-manager-1.20.0.tar.xz : 4f5c4068f3e1f4d63bb86340b375c2f73dec8fb54066d7da589f70a89337f96f
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Session Management
description: |
    MATE Session Management
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libsystemd)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - xtrans
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
