name       : mate-session-manager
version    : 1.20.2
release    : 12
source     :
    - https://github.com/mate-desktop/mate-session-manager/archive/v1.20.2.tar.gz : 37481c4d4685598ead0606e005eced5889dcacbcccb6e3192de11a75eb79496e
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libsystemd)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - mate-common
    - yelp-devel
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
