name       : mate-session-manager
version    : 1.24.1
release    : 20
source     :
    - https://github.com/mate-desktop/mate-session-manager/releases/download/v1.24.1/mate-session-manager-1.24.1.tar.xz : a1c472a3da20c2c69b1de9f2746f23ceaf149bb633fb8b8496715c5fbd4698ff
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xau)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
