name       : mate-session-manager
version    : 1.24.2
release    : 21
source     :
    - https://github.com/mate-desktop/mate-session-manager/releases/download/v1.24.2/mate-session-manager-1.24.2.tar.xz : 6b0b9c0c4fe831e4f000e55a2ebb953cf2a83eed613faaf3e23c8beec42c8bc9
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xau)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
