name       : mate-session-manager
version    : 1.22.0
release    : 13
source     :
    - https://github.com/mate-desktop//mate-session-manager/archive/v1.22.0.tar.gz : ee9ae4216ca2ad63b216e13e68f75634b58d804f758000f921f12413b4b02bc5
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xau)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - mate-common
    - yelp-devel
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
