name       : mate-session-manager
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-session-manager-1.14.1.tar.xz : 26bb04472e19d637db6e9653235d5343dd7b6f2a128a4d2b19366a8bd01d4502
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Session Management
description: |
    MATE Session Management
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(sm)
    - pkgconfig(ice)
    - pkgconfig(xext)
    - pkgconfig(xau)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsystemd)
    - pkgconfig(upower-glib)
    - pkgconfig(xtst)
    - pkgconfig(xrender)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
