name       : mate-session-manager
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-session-manager-1.16.0.tar.xz : 15a5b986c6ba32bab381ed68d21d50ca14fdbe1e2c28ca990a833f21539b41c6
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Session Management
description: |
    MATE Session Management
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(sm)
    - pkgconfig(ice)
    - pkgconfig(xext)
    - pkgconfig(xau)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsystemd)
    - pkgconfig(upower-glib)
    - pkgconfig(xtst)
    - pkgconfig(xrender)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
