name       : mate-session-manager
version    : 1.20.1
release    : 11
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-session-manager-1.20.1.tar.xz : 251eec7ae8a79627d736138c6eb87206f4bf53ba772210f3d5dd017d0d51bd3d
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    MATE Session Management
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(libsystemd)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
