name       : mate-session-manager
version    : 1.22.1
release    : 14
source     :
    - https://github.com/mate-desktop/mate-session-manager/archive/v1.22.1.tar.gz : 8e8c7a903e0805d42f0fa05b7e391b9c2b9341a679b56ff994932ee83b7fa9b8
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xau)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - mate-common
    - yelp-devel
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
