name       : mate-session-manager
version    : 1.22.2
release    : 16
source     :
    - https://github.com/mate-desktop/mate-session-manager/archive/v1.22.2.tar.gz : 5b022287979ea468fc54966f67ee1045a83fa4f0225708ae4a092bccc2abba83
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Session Management
description: |
    mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xau)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - mate-common
    - yelp-devel
    - xtrans
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs-gtk
    - xdg-utils
    - xtrans
setup      : |
    %patch -p1 < $pkgfiles/0001_fix_gnome_keyring_timeout.patch
    %patch -p1 < $pkgfiles/0005_lock-session-before-user-switch.patch

    %autogen
build      : |
    %make
install    : |
    %make_install
